[project]
name = "jarvis"
version = "0.1.0"
description = ""
authors = [
    {name = "Yutong Jiang", email = "yutongj2@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.7.0,<3.0.0",
    "transformers>=4.56.2",
]

[project.optional-dependencies]
speech2text = [
    "pyaudio>=0.2.14,<0.3.0",
    "sounddevice>=0.5.2,<0.6.0",
    "vosk>=0.3.45,<0.4.0",
    "webrtcvad>=2.0.10,<3.0.0",
    "scipy>=1.15.3,<2.0.0",
    "numpy>=2.2.6,<3.0.0"
]
data = [
    "pandas>=2.2.3,<3.0.0"
]
tts = [

]
llm-agents = [
    "geopy>=2.4.1",
    "langchain-community>=0.3.30",
    "langchain-openai>=0.3.33",
    "langgraph>=0.6.0",
    "mcp>=1.15.0",
    "pytz>=2025.2",
    "timezonefinder>=8.1.0",
    "transformers>=4.52.4,<5.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/jarvis"]
