name: 🚨 Secret Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          args: --verbose --redact
