name: 🚨 Secret Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
        - master
        - 'dev/**'

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose --redact
